name: Build Redisearch for Windows

on:
  push:
    branches:
      - main  # 监控 main 分支的推送
  pull_request:
    branches:
      - main  # 监控 PR 到 main 分支

jobs:
  build:
    runs-on: windows-2025  # 使用 Windows Server 2025 环境

    steps:
      # 1. 设置调试模式
      - name: Set up debugging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      # 2. 检查 Git 是否正确安装
      - name: Check Git Version
        run: |
          git --version  # 打印 git 版本
          where git  # 查看 git 路径

      # 3. 检出代码，指定明确的仓库和分支
      - name: Checkout Redisearch repository
        uses: actions/checkout@v3  # 使用最新版本 v3
        with:
          repository: RediSearch/RediSearch  # 确保仓库名称正确
          ref: main  # 如果分支是 main，改成 main
          token: ${{ secrets.GITHUB_TOKEN }}  # 如果是私有仓库，使用 GitHub Token 认证
          fetch-depth: 0  # 获取完整历史，避免浅克隆问题

      # 4. 列出当前文件，检查仓库是否正确检出
      - name: List files after checkout
        run: |
          Get-ChildItem -Force  # 列出当前目录内容

      # 5. 安装 MSYS2 和 Git
      - name: Install MSYS2 and Git
        run: |
          choco install msys2 -y  # 安装 MSYS2
          refreshenv  # 刷新环境变量
          C:\tools\msys64\usr\bin\bash.exe -l -c "pacman -S --noconfirm git"  # 安装 Git
          C:\tools\msys64\usr\bin\bash.exe -l -c "git --version"  # 确认安装成功

      # 6. 克隆 Redis 仓库
      - name: Clone Redis repository
        run: |
          git clone --single-branch https://github.com/redis/redis.git  # 克隆 Redis 仓库

      # 7. 更新 MSYS2 并安装依赖项
      - name: Install Redisearch Dependencies
        run: |
          C:\tools\msys64\usr\bin\bash.exe -l -c "pacman -Syu --noconfirm"  # 更新 MSYS2
          C:\tools\msys64\usr\bin\bash.exe -l -c "pacman -S --noconfirm make gcc cmake"  # 安装 make, gcc, cmake 工具

      # 8. 配置 Redisearch 项目
      - name: Configure Redisearch with CMake
        run: |
          mkdir build  # 创建构建目录
          cd build
          cmake -G "MSYS Makefiles" -D CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=YES ..  # 设置 CMake 来构建 DLL

      # 9. 构建 Redisearch
      - name: Build Redisearch
        run: |
          cd build
          make  # 编译 Redisearch

      # 10. 列出构建目录中的文件，确保 DLL 文件生成
      - name: List build files after build
        run: |
          Get-ChildItem -Recurse -Force

      # 11. 上传构建产物
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4  # 使用最新版的 upload-artifact
        with:
          name: redisearch-windows-build  # 指定构建产物的名称
          path: build/  # 上传构建目录中的文件
